---
title: "teste"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# {.tabset .tabset-fade .tabset-pills}


## Tab 1


* item 2
 + sub-item 1
 + sub-item 2 

``` {r include=F }
library(dplyr)

hsm_df <- read.csv("donnees/REG1903b_3_Frontiers_HSM_Burkina_Faso_2021-03-16.csv", 
                   na.strings = c("NA", "", "N/A", "N.A.", "NnA"),
                   encoding = "UTF-8")

hsm_df$statut_deplace_recode <- case_when(hsm_df$statut_deplacement == "PDI (personne déplacée interne dans son pays)" ~ "PDI",
                                          hsm_df$statut_deplacement == "Population non déplacée (personne résidant dans la localité et ne s'étant pas déplacée)" ~ "non_deplacee",
                                          hsm_df$statut_deplacement == "Retourné (personne auparavant déplacée dans son pays qui est désormais retournée chez elle)" ~ "retournee")


```

grouper et faire une sommaire des donnees
``` {r echo=T, eval=T, warning=F, message=F}
hsm_admin1_group <- hsm_df %>% 
  group_by(admin1) %>% 
  summarize(n_enquetes = n())

library(formattable)

formattable(hsm_admin1_group, list(
  n_enquetes = color_tile("#c9ffe0", "#2b9e5c")
))


```

grouper par admin2
``` {r echo=T, eval=T, warning=F, message=F}
hsm_admin2_groupe <- hsm_df %>% 
  group_by(admin1, admin2) %>% 
  summarize(n_enquetes = n(),
            n_restants = 250 - n_enquetes)

formattable(hsm_admin2_groupe, list(
  n_enquetes = color_bar("lightblue"),
  n_restants = color_tile("#A5C9A1", "#EE5859")
))

```

formattable avec la fonction data.table
``` {r echo=T, eval=T, warning=F, message=F}
hsm_admin2_groupe <- hsm_df %>% 
  group_by(admin1, admin2) %>% 
  summarize(n_enquetes = n(),
            n_restants = 250 - n_enquetes)

as.datatable(formattable(hsm_admin2_groupe, list(
  n_enquetes = color_bar("lightblue"),
  n_restants = color_tile("#A5C9A1", "#EE5859")
)), options = list(pageLength = 20))

```


formattable avec la fonction data.table
``` {r echo=T, eval=T, warning=F, message=F}
hsm_admin2_groupe <- hsm_df %>% 
  group_by(admin1, admin2, statut_deplace_recode) %>% 
  summarize(n_enquetes = n())

hsm_admin2_groupe <- hsm_admin2_groupe %>% 
  mutate(eschantionnage = case_when(statut_deplace_recode == "PDI" ~ 80, 
                                    statut_deplace_recode == "non_deplacee" ~ 180, TRUE ~ 10))

hsm_admin2_groupe <- hsm_admin2_groupe %>% 
  mutate(n_restant = eschantionnage - n_enquetes)

as.datatable(formattable(hsm_admin2_groupe, list(
  n_enquetes = color_bar("lightblue"),
  n_restant = color_tile("#A5C9A1", "#EE5859")
)), options = list(pageLength = 40))

```